name: SI PY compilation check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: create an executable
      run: |
        pyinstaller --exclude-module bleak.backends.corebluetooth --name "Smart Instrument Interface" --onefile --hidden-import winrt --hidden-import winrt.windows.foundation --hidden-import winrt.windows.devices.bluetooth --hidden-import winrt.windows.foundation.collections --hidden-import bleak.backends.winrt.scanner --hidden-import bleak.backends.winrt.client --collect-all winrt --collect-all bleak main.py
    - name: list all files
      run: |
        ls -LR
    - name: check if the file exists
      run: |
        if [ ! -f "dist/Smart Instrument Interface" ]; then
          echo "Error: dist/Smart Instrument Interface executable not found!" >&2
          exit 1
        fi
